### ISSUE TITLE
Vim stuttering when using vim-you-autocorrect in Goyo.vim environment

### ISSUE THREAD

**Issue by abot3667** [sedm0784/vim-you-autocorrect#5] opened 2020-05-12 18:21 UTC
I am new to submitting issues FYI: 

See here for video : https://cdn.discordapp.com/attachments/662739415285628928/709818333725327440/2020-05-12_13-14-19.mp4 

Shown above is stuttering that occurs when vim-you-autocorrect and Goyo.vim interact, the autocorrect plugin still works but it causes stuttering when I press `space` key in the :Goyo environment.

It should be able to be replicated using : 
`vim --v `: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  8 2020 23:37:13)
`vim-plug` : https://github.com/junegunn/vim-plug
`vim-you-autocorrect`: https://github.com/sedm0784/vim-you-autocorrect
`goyo.vim` : https://github.com/junegunn/goyo.vim

Should be able to be replicated with following .vimrc :

```
call plug#begin()

" Autocorrect
Plug 'sedm0784/vim-you-autocorrect'

" Distraction free writing in Vim
Plug 'junegunn/goyo.vim'

call plug#end()
```

Then I open up my .tex file. (I can include mine if you cannot replicate it on your end.)
Then I :Goyo and :EnableAutocorrect  into the file. 
Then the stuttering begins when I press space key at any point in the file. 

Please let me know if there are any issues with my explanation.

Best, 

Love the plugin btw.

**Comment by ShogunHirei** [comment] 2020-09-08 17:15
I have observed this behavior too. In my case the screen centers and returns to the position before real quickly. I have observed this behavior before installation of Goyo and LimeLigth.

**Comment by sedm0784** [comment] 2021-01-04 10:41
Oh hey, I'm sorry I didn't reply sooner: I didn't notice the notification in GitHub. I'll take a look and see if I can figure out what is going wrong, and whether it's possible to fix it.

**Comment by ShogunHirei** [comment] 2021-01-28 11:53
Hi @sedm0784 and @abot3667! I don't know if you are tracking this issue anymore but I'd like to add some info about the stuttering in the screen.

I realized that the screen doesn't change if the last wrong character is in the screen. I guess that the `]s` used to verify the last word goes back way up to the beginning of file if the last typed word is right. **Still, I didn't tested it thoroughly.** 

To fix this I planted a wrong char in the screen (like `açlskdnaçoiubn`) so it doesn't stutter.

Pretty good job with the plugin, really helpful!

**Comment by sedm0784** [comment] 2021-01-28 17:21
I haven't had a chance to look into this in detail, but I do intend to do so when I get a chance. Thanks for the extra info. Sounds like something (possibly multiple things if one of you has seen it without Goyo) is causing an unwanted redraw while the autocorrect function is running. I'm not sure whether there will be anything that I can do about in Vim You, Autocorrect!, because invoking `[s` is pretty fundamental to how it works&#8202;&mdash;&#8202;I'm not aware of any other good mechanism I could replace it with&#8202;&mdash;&#8202;but hopefully it will be possible for me to suggest changes to the conflicting plugin(s) to fix the issue, if I can track it down.

One quick question for both of you (@abot3667 and @ShogunHirei): does the issue appear both in GUI Vim and in the Terminal, or just in one of these?

**Comment by sedm0784** [comment] 2021-01-28 17:36
...actually I may have just figured out a workaround. Watch this space!

**Comment by sedm0784** [comment] 2021-01-29 10:26
Hi @abot3667, @ShogunHirei,

I've just pushed a fix to the `gh5_flicker` branch. If you are using vim-plug I believe you can test this out by changing your config line to:

    Plug 'sedm0784/vim-you-autocorrect', { 'branch': 'gh5_flicker' }

Let me know whether this seems to fix the issue. (I couldn't reproduce it, with or without Goyo.)

Thanks for your patience!

**Comment by ShogunHirei** [comment] 2021-01-29 14:02
@sedm0784 

Tested it now! So far so good!

Thank you for the plugin, goodwill and readiness! 

PS: branch name has underscore, `gh5`**_**`flicker`.

**Comment by sedm0784** [comment] 2021-01-29 14:21
Terrific, that's great to hear. I'll merge this into master then, and do a point release. Thanks for testing out my fix so promptly!

P.S. Fixed the underscore, too. Thanks.

**Closed as completed** 2021-01-29 15:00 UTC
Labels: bug
